frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\models\Accounts;
use common\models\Trades;
use frontend\components\UsersComponent;
use frontend\models\CalculateTrades;
use yii\web\Controller;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index', ['usersComponent' => new  UsersComponent()]);
    }

    /**
     * @return mixed
     */
    public function actionCalculateTrades()
    {
        $model = new CalculateTrades();
        $accounts =
            Accounts::find()
                ->asArray()
                ->limit(5000)
                ->all()
        ;

        $result = [];

        if ($model->load(\Yii::$app->request->post())) {
            $result = Trades::receivesTrades($model->login, $model->start_date, $model->end_date);
        }

        return $this->render('calculate-trades', compact('model', 'result', 'accounts'));
    }
}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems =
        [
            ['label' => 'List Users', 'url' => ['/site/index']],
            ['label' => 'Calculate Trades', 'url' => ['/site/calculate-trades']],
        ];

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>